// Facilitator-facing strings only. Player-facing screens use NO text at all
// (rule: zero text dependence — everything is demonstrated or iconic).
// Default Portuguese (Brazil); swap this table to translate the facilitator UI.
export const STR = {
  appTitle: 'Sound Hunters — protótipo',
  facilitator: 'Facilitador',
  language: 'Língua',
  newLanguage: 'Nova língua…',
  languageName: 'Nome da língua',
  speakers: 'Falantes',
  addSpeaker: 'Adicionar falante',
  alias: 'Nome ou apelido',
  ageBand: 'Faixa etária',
  gender: 'Gênero',
  optional: '(opcional)',
  consent: 'Consentimento verbal registrado (gravação de voz e uso para pesquisa)',
  consentRequired: 'Marque o consentimento para iniciar a sessão.',
  startSession: 'Iniciar sessão',
  resumeSession: 'Continuar sessão de hoje',
  activeSession: 'Sessão ativa',
  endSession: 'Encerrar sessão',
  deck: 'Baralho (deck)',
  deckVersion: 'Versão',
  items: 'itens',
  dashboard: 'Painel de coleta',
  repsMatrix: 'Itens × repetições',
  coreProgress: 'Núcleo de calibração por falante',
  coreLabel: 'núcleo',
  expansionLabel: 'expansão',
  level: 'Nível',
  basketsDone: 'Rodadas de cesta concluídas',
  freeRecordings: 'Gravações livres (arquivo)',
  convergence: 'Convergência entre falantes (itens do núcleo)',
  convergencePairs: 'pares convergem',
  noJudgmentsYet: 'sem verificação ainda',
  export: 'Exportar ZIP',
  exporting: 'Exportando…',
  canonicalReview: 'Revisar tomada canônica',
  pickCanonical: 'Toque na estrela para definir a tomada canônica.',
  auto: 'auto',
  manual: 'manual',
  quality: 'qualidade',
  devMode: 'Modo dev',
  devPanel: 'Painel dev',
  spacing: 'Espaçamento mínimo (itens entre repetições)',
  dailyCap: 'Máx. repetições por item por dia',
  seedDemo: 'Semear dados de demonstração (2 falantes)',
  seeding: 'Semeando…',
  seeded: 'Dados de demonstração criados.',
  wipe: 'Apagar TODOS os dados locais',
  wipeConfirm: 'Apagar tudo? Esta ação não pode ser desfeita.',
  playerScreens: 'Telas do jogador (sem texto)',
  phase1: 'Fase 1 — Nomear figuras',
  phase2: 'Fase 2 — Cestas de sons',
  phase3: 'Fase 3 — Gêmeas',
  voicesCheck: 'Vozes — convergência',
  freeArea: 'Arte verbal (livre)',
  needSession: 'Inicie uma sessão com um falante para abrir as telas do jogador.',
  needMic: 'Este navegador não liberou o microfone. Verifique as permissões.',
  judge: 'Quem julga?',
  judgeHint: 'O juiz pode ser um terceiro falante ou um dos dois comparados.',
  attribution: 'Atribuição (quem ensinou)',
  attributionVoice: 'Gravar atribuição em voz',
  reuseConsent: 'Consentimento de reuso (facilitador)',
  close: 'Fechar',
  save: 'Salvar',
  cancel: 'Cancelar',
  takes: 'tomadas',
  noTakes: 'Nenhuma gravação ainda.',
  speakerNeeded: 'Cadastre ao menos um falante.',
  exportNote: 'O ZIP contém audio/<id>.<ext> + manifest.json (esquema do contrato de dados).',
  sessionDevice: 'dispositivo',
  voicesLocked: 'Disponível quando 2+ falantes tiverem tomada canônica de um item do núcleo.',
  pairsToJudge: 'pares para julgar',
};

export const AGE_BANDS = ['', '18–30', '31–45', '46–60', '60+'];
export const GENDERS = ['', 'feminino', 'masculino', 'outro'];
